### ISSUE TITLE
Search everything

### ISSUE THREAD

**Issue by mushon** [OpenBudget/open-budget-frontend#187]
תמיכות העברות והכל צריך להיות חפיש
צריך גם תוצאות חיפוש…

**Comment by akariv** [comment]
@naamac sorry for the long time to respond.

In order to search everything we need to:
a) Fix the script that generates the search index:
https://github.com/OpenBudget/open-budget-data/blob/master/processors/make_search_prefixes.py

b) fix the API server to support other kinds of elements:
https://github.com/OpenBudget/open-budget-api/blob/master/open-budget-il/main.py#L509

c) replace the API call in the frontend and support receiving results of multiple kinds.

**Comment by naamac** [comment]
Hi, 
just wanted to update @shayshei and me are working on it. 
but we won't come today (sorry!)

**Comment by mushon** [comment]
This is on hold pending OpenSpending backend investigation #208
